// The guide page. Reads window.GUIDE (data.js, generated by tools/build-guide.mjs from the game) and
// builds every section from it. Nothing here knows a key, a symbol or a word of the game by heart.
(() => {
  'use strict';
  const G = window.GUIDE;
  if (!G) { document.getElementById('asof').textContent = 'The guide data did not load.'; return; }
  const $ = (id) => document.getElementById(id);
  const E = G.entries;
  const PAL = G.symbology.palette;
  const SYM = G.symbology.symbols;

  // ------------------------------------------------------------------------------------ text
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const SECTION_NAMES = { find: 'Find a control', console: 'The console', symbols: 'Symbols', lessons: 'Training', mission: 'Mission 1', alerts: 'Alerts', glossary: 'Glossary', controls: 'Touch & keyboard', menus: 'Menus & scoring', scoring: 'Menus & scoring' };
  /** `code`, **bold**, [[entry]] and [[#section]] — the only markup content.js uses */
  function md(s) {
    return esc(s)
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\[\[#([^\]]+)\]\]/g, (_, id) => `<a href="#${id === 'scoring' ? 'menus' : id}">${esc(SECTION_NAMES[id] || id)}</a>`)
      .replace(/\[\[([^\]]+)\]\]/g, (_, id) => xref(id));
  }
  const shortTitle = (e) => e.title.split(':')[0];
  const xref = (id, text) => { const e = E[id]; return e ? `<a class="xref" data-e="${esc(id)}" href="#console">${esc(text || shortTitle(e))}</a>` : esc(text || id); };

  // ------------------------------------------------------------------------------------ where
  const legendOf = (e) => e.title.split(':')[0].replace(/ page$/, '');
  const HELM_ORDER = ['crs', 'spd', 'rud'];
  /** "EW page → CHAF", "SENS page → MORE → EMCN", "Keypad → DECOY" — the path a finger takes */
  function wherePath(e, w) {
    const k = legendOf(e);
    switch (w.kind) {
      case 'fixed': return ['Keypad', k];
      case 'tab': return ['Page tab', k];
      case 'soft': return [`${w.page.toUpperCase()} page`, ...Array(w.bank - 1).fill('MORE'), k];
      case 'helm': return ['HELM', ...Array(HELM_ORDER.indexOf(w.group)).fill('MORE'), k];
      case 'screen': return [w.page === 'helm' ? 'Helm mode' : `${w.page.toUpperCase()} page`];
      default: return [k];
    }
  }
  const pathHtml = (parts) => parts.map((p, i) => (i ? '<span class="arr">→</span>' : '') + esc(p)).join('');
  function whereChips(id, { max = 6 } = {}) {
    const e = E[id]; if (!e) return '';
    const seen = new Set();
    const chips = [];
    for (const w of e.where) {
      const p = wherePath(e, w); const key = p.join('>');
      if (seen.has(key)) continue; seen.add(key);
      chips.push(`<button class="chip where" data-e="${esc(id)}" data-shot="${esc(w.shot)}" title="Show it on the console">${pathHtml(p)}</button>`);
    }
    for (const k of e.kbd) chips.push(`<span class="chip">Key <kbd>${esc(k)}</kbd></span>`);
    return chips.slice(0, max + e.kbd.length).join(' ');
  }

  // ------------------------------------------------------------------------------------ console
  const shots = Object.fromEntries(G.shots.map((s) => [s.id, s]));
  const W = G.meta.virtual.w, H = G.meta.virtual.h;
  let cur = 'ops-1', selected = null;
  const PAGES = ['ops', 'air', 'surf', 'wpn', 'ew', 'sens'];

  function renderPagebar() {
    const s = shots[cur];
    $('pagebar').innerHTML = [...PAGES, 'helm'].map((p) => {
      const on = s.helm ? p === 'helm' : (s.page === p);
      return `<button class="chip" role="tab" aria-selected="${on}" aria-pressed="${on}" data-go="${p}">${p.toUpperCase()}</button>`;
    }).join('') + (s.bank && shots[`${s.page}-2`] ? `<span class="chip" aria-hidden="true" style="cursor:default;color:var(--frame6)">bank ${s.bank}</span>` : '') +
      (s.helm ? `<span class="chip" aria-hidden="true" style="cursor:default;color:var(--frame6)">${{ crs: 'course', spd: 'speed', rud: 'rudder' }[s.helm]}</span>` : '');
  }
  function setShot(id) {
    if (!shots[id]) return;
    cur = id;
    const s = shots[id];
    $('shot').src = s.img;
    $('shot').alt = `The console on the ${s.helm ? 'helm' : s.page.toUpperCase()} page`;
    const pct = (v, of) => `${(v / of) * 100}%`;
    $('spots').innerHTML = s.hotspots.map((h, i) => {
      const e = E[h.e];
      const region = h.e === 'region:plot' || h.e === 'region:alert';
      return `<button class="spot${region ? ' region' : ''}" data-i="${i}" style="left:${pct(h.x, W)};top:${pct(h.y, H)};width:${pct(h.w, W)};height:${pct(h.h, H)}" aria-label="${esc(e ? e.title : h.e)}"></button>`;
    }).join('');
    renderPagebar();
    markSelected();
  }
  function markSelected(flash) {
    let first = null;
    for (const b of $('spots').children) {
      const h = shots[cur].hotspots[b.dataset.i];
      const on = selected && h.e === selected && h.e !== 'region:plot';
      b.classList.toggle('sel', !!on);
      if (on && !first) first = b;
      if (on && flash) { b.classList.remove('flash'); void b.offsetWidth; b.classList.add('flash'); }
    }
    // the phone's scrolling frame: bring the selection into it, or start on the panel
    const sc = $('scroller');
    if (sc.scrollWidth > sc.clientWidth) {
      const x = first ? first.offsetLeft + first.offsetWidth / 2 - sc.clientWidth / 2 : sc.scrollWidth;
      sc.scrollTo({ left: Math.max(0, x), behavior: flash ? 'smooth' : 'auto' });
    }
  }
  function go(target) {
    const s = shots[cur];
    if (target.page) setShot(`${target.page}-1`);
    else if (target.helm) setShot('helm-crs');
    else if (target.more) {
      if (s.helm) setShot(`helm-${HELM_ORDER[(HELM_ORDER.indexOf(s.helm) + 1) % 3]}`);
      else setShot(shots[`${s.page}-${s.bank + 1}`] ? `${s.page}-${s.bank + 1}` : `${s.page}-1`);
    }
  }

  function showEntry(id, { shot, scroll, flash } = {}) {
    const e = E[id]; if (!e) return;
    selected = id;
    if (shot && shot !== cur) setShot(shot);
    const lamps = e.lamp ? `<p class="lbl">Lamp</p><ul class="lamps">${Object.entries(e.lamp).map(([c, t]) => `<li><span class="lamp ${c}"></span><span><b>${c}</b>: ${md(t)}</span></li>`).join('')}</ul>` : '';
    const where = whereChips(id);
    $('detail').innerHTML =
      `<h4>${esc(e.title)}</h4><p class="sum">${md(e.summary)}</p>` +
      e.body.map((p) => `<p>${md(p)}</p>`).join('') + lamps +
      (where ? `<p class="lbl">Where</p><div class="chips">${where}</div>` : '') +
      (e.see.length ? `<p class="lbl">See also</p><div class="chips">${e.see.map((s) => s.startsWith('#') ? `<a class="chip" href="${s === '#scoring' ? '#menus' : s}">${esc(SECTION_NAMES[s.slice(1)] || s)}</a>` : `<button class="chip" data-e="${esc(s)}">${esc(E[s] ? shortTitle(E[s]) : s)}</button>`).join('')}</div>` : '');
    markSelected(flash);
    if (scroll) $('console').scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
  /** open an entry from anywhere on the page: on the console if it is on the console, else in place */
  function open(id, shot) {
    const e = E[id]; if (!e) return;
    const onScreen = shot || (shots[cur].hotspots.some((h) => h.e === id) ? cur : (e.where[0] && e.where[0].shot));
    showEntry(id, { shot: onScreen, scroll: true, flash: true });
  }

  $('spots').addEventListener('click', (ev) => {
    const b = ev.target.closest('.spot'); if (!b) return;
    const h = shots[cur].hotspots[b.dataset.i];
    if (h.go) { go(h.go); }
    showEntry(h.e);
  });
  $('pagebar').addEventListener('click', (ev) => {
    const b = ev.target.closest('[data-go]'); if (!b) return;
    const p = b.dataset.go;
    go(p === 'helm' ? { helm: true } : { page: p });
    showEntry(p === 'helm' ? 'soft:ops:HELM' : `tab:${p}`);
  });
  $('showall').addEventListener('change', (ev) => $('screen').classList.toggle('showall', ev.target.checked));
  // every [data-e] anywhere on the page opens that entry
  document.addEventListener('click', (ev) => {
    const a = ev.target.closest('[data-e]');
    if (!a || a.classList.contains('spot')) return;
    ev.preventDefault();
    open(a.dataset.e, a.dataset.shot);
  });

  // ------------------------------------------------------------------------------------ find
  // Search: field-weighted term scoring with inverse document frequency — a small BM25F. Each query word
  // scores by WHERE it matches (the on-screen legend beats the title beats an alias beats the prose),
  // weighted by how rare it is across the guide, so "chaff" outweighs "the". Entries matching every word
  // outrank those matching some, and an entry that is a control you can press gets a small lift.
  const STOP = new Set('a an and are as at be by do for from how i in is it of on or the to what when where which with you your'.split(' '));
  const words = (s) => s.toLowerCase().replace(/[`*[\]]/g, ' ').split(/[^a-z0-9▲+\-]+/).filter((w) => w && !STOP.has(w));
  const FIELD_WEIGHT = { label: 10, title: 5, aliases: 4, summary: 2, body: 1 };
  const index = Object.values(E).map((e) => ({
    id: e.id, e, title: e.title.toLowerCase(),
    f: {
      // only "LABEL: what it does" and "OPS page" titles carry an on-screen legend; "Chaff cloud" does not
      label: /:| page$/.test(e.title) ? words(legendOf(e)) : [], title: words(e.title), aliases: words(e.aliases.join(' ')),
      summary: words(e.summary), body: words(e.body.join(' ')),
    },
    control: /^(key|tab|soft|helm):/.test(e.id),
  }));
  for (const it of index) it.all = new Set(Object.values(it.f).flat());
  const idf = (() => {
    const df = new Map();
    for (const it of index) for (const w of it.all) df.set(w, (df.get(w) || 0) + 1);
    const N = index.length;
    return (w) => Math.log(1 + (N - (df.get(w) || 0) + 0.5) / ((df.get(w) || 0) + 0.5));
  })();

  /** how strongly one field's words match one query word: exact 1, prefix either way (3+ letters) 0.6 */
  function fieldMatch(fieldWords, t) {
    let best = 0;
    for (const w of fieldWords) {
      if (w === t) return 1;
      if (t.length >= 3 && w.length >= 3 && (w.startsWith(t) || t.startsWith(w))) best = 0.6;
    }
    return best;
  }

  /** 0 leaves the entry out; higher ranks first */
  function scoreEntry(item, q, terms) {
    let score = 0, matched = 0;
    for (const t of terms) {
      let s = 0;
      for (const [field, weight] of Object.entries(FIELD_WEIGHT)) s += weight * fieldMatch(item.f[field], t);
      if (s > 0) { matched++; score += s * idf(t); }
    }
    if (!matched) return 0;
    score *= matched / terms.length;                       // coverage: every word beats some words
    if (terms.length > 1 && (item.title.includes(q) || item.e.aliases.some((a) => a.toLowerCase().includes(q)))) score *= 1.5;  // the phrase itself
    if (item.e.aliases.some((a) => a.toLowerCase() === q)) score *= 2;  // the query IS one of its synonyms ("fire" → ENG)
    if (item.control) score *= 1.2;                        // a key you can press beats a readout about it
    return score;
  }

  function search(raw) {
    const q = raw.trim().toLowerCase();
    if (!q) { $('results').innerHTML = ''; return; }
    const terms = words(q);
    if (!terms.length) { $('results').innerHTML = ''; return; }
    const hits = index.map((it) => ({ it, s: scoreEntry(it, q, terms) })).filter((h) => h.s > 0)
      .sort((a, b) => b.s - a.s || a.it.title.localeCompare(b.it.title)).slice(0, 12);
    $('results').innerHTML = hits.length ? hits.map(({ it }) => {
      const e = it.e;
      return `<li><button class="rt" data-e="${esc(e.id)}">${esc(e.title)}</button><div class="rs">${md(e.summary)}</div><div class="chips">${whereChips(e.id, { max: 4 })}</div></li>`;
    }).join('') : `<li class="none">Nothing matches "${esc(raw)}". Try a word from the screen, like <code>CPA</code>, or what you want to do, like "zoom".</li>`;
  }
  let t = 0;
  $('q').addEventListener('input', (ev) => { clearTimeout(t); t = setTimeout(() => search(ev.target.value), 80); });

  // ------------------------------------------------------------------------------------ pixels
  function drawRows(ctx, rows, x, y, color) {
    ctx.fillStyle = color;
    for (let r = 0; r < rows.length; r++) for (let c = 0; c < rows[r].length; c++) if (rows[r][c] !== '.') ctx.fillRect(x + c, y + r, 1, 1);
  }
  function drawText(ctx, str, x, y, fontName, color) {
    const f = G.symbology.font[fontName];
    for (const ch of String(str)) { const g = f.glyphs[ch] || f.glyphs[ch.toUpperCase()]; if (g) drawRows(ctx, g, x, y, color); x += f.advance; }
  }
  function line(ctx, x0, y0, x1, y1, color) {      // Bresenham, as the plot draws its leaders
    ctx.fillStyle = color;
    x0 = Math.round(x0); y0 = Math.round(y0); x1 = Math.round(x1); y1 = Math.round(y1);
    const dx = Math.abs(x1 - x0), dy = -Math.abs(y1 - y0), sx = x0 < x1 ? 1 : -1, sy = y0 < y1 ? 1 : -1;
    let err = dx + dy;
    for (;;) { ctx.fillRect(x0, y0, 1, 1); if (x0 === x1 && y0 === y1) break; const e2 = 2 * err; if (e2 >= dy) { err += dy; x0 += sx; } if (e2 <= dx) { err += dx; y0 += sy; } }
  }
  /** a symbol with its sea-coloured halo, centred on (cx, cy) as the plot centres it */
  function drawSymbol(ctx, key, cx, cy, color) {
    const rows = SYM[key]; if (!rows) return 0;
    const hs = rows[0].length >> 1;
    if (SYM[key + '_H']) drawRows(ctx, SYM[key + '_H'], cx - hs - 1, cy - hs - 1, PAL.SEA0);
    drawRows(ctx, rows, cx - hs, cy - hs, color);
    return hs;
  }
  function canvasFor(w, h, scale) {
    const c = document.createElement('canvas'); c.width = w; c.height = h;
    c.style.width = `${w * scale}px`; c.style.height = `${h * scale}px`;
    return c;
  }

  // ------------------------------------------------------------------------------------ symbols
  const IDS = G.symbology.identities;
  const CATS = [...G.symbology.categories, { cat: 'MSL', name: 'Missile', text: 'An arrowhead pointing where it flies.' }];
  const RAMP = { FRD: ['FRD0', 'FRD1', 'FRD2'], HOS: ['HOS0', 'HOS1', 'HOS2'], NEU: ['NEU0', 'NEU1', 'NEU1'], UNK: ['UNK0', 'UNK1', 'UNK1'] };
  const dir8 = (deg) => Math.round(((deg % 360) + 360) % 360 / 45) % 8;
  const symKey = (idn, cat, hdg) => cat === 'MSL' ? `MSL${dir8(hdg)}` : `${idn.shape}_${cat}`;

  function buildGrid() {
    const g = $('symgrid');
    let html = '<div></div>' + IDS.map((i) => `<div class="h">${i.idn}</div>`).join('');
    for (const c of CATS) {
      html += `<div class="rh">${c.cat === 'SUR' ? 'SURFACE' : c.cat === 'SUB' ? 'SUBSURF' : c.cat === 'MSL' ? 'MISSILE' : 'AIR'}</div>`;
      html += IDS.map((i) => `<button data-idn="${i.idn}" data-cat="${c.cat}" aria-label="${esc(i.name)}, ${esc(c.name)}"></button>`).join('');
    }
    g.innerHTML = html;
    for (const b of g.querySelectorAll('button')) {
      const i = IDS.find((x) => x.idn === b.dataset.idn);
      const cv = canvasFor(11, 11, 3); const ctx = cv.getContext('2d');
      drawSymbol(ctx, symKey(i, b.dataset.cat, 45), 5, 5, PAL[i.color]);
      b.appendChild(cv);
    }
    g.addEventListener('click', (ev) => {
      const b = ev.target.closest('button'); if (!b) return;
      lab.idn = b.dataset.idn; lab.cat = b.dataset.cat; drawLab();
      $('lab').scrollIntoView({ behavior: 'smooth', block: 'center' });
    });
  }

  const lab = { idn: 'HOS', cat: 'SUR', hdg: 315, on: new Set(['leader', 'history', 'label']) };
  const LAB_STATES = [
    { id: 'leader', name: 'Leader' }, { id: 'history', name: 'History' }, { id: 'label', name: 'Label' },
    ...G.symbology.states.map((s) => ({ id: s.id, name: s.name, text: s.text })),
  ];
  function drawLab() {
    const cv = $('lab'); const ctx = cv.getContext('2d');
    ctx.fillStyle = PAL.SEA1; ctx.fillRect(0, 0, cv.width, cv.height);
    const i = IDS.find((x) => x.idn === lab.idn);
    const on = (k) => lab.on.has(k);
    const ramp = RAMP[i.shape];
    let lvl = 1;
    if (on('tentative')) lvl = 0;
    if (on('stale')) lvl = Math.max(0, lvl - 1);
    if (on('hooked') || on('engaged')) lvl = 2;
    const col = PAL[i.idn === 'SUS' ? 'UNK0' : ramp[lvl]];
    const cx = 30, cy = 30;
    const r = (lab.hdg * Math.PI) / 180, dx = Math.sin(r), dy = -Math.cos(r);
    if (on('history')) for (const d of [6, 10, 14, 18]) { ctx.fillStyle = PAL[ramp[1]]; ctx.fillRect(Math.round(cx - dx * d), Math.round(cy - dy * d), 1, 1); }
    const key = symKey(i, lab.cat, lab.hdg);
    const hs = SYM[key][0].length >> 1;
    if (on('leader')) line(ctx, cx + dx * (hs + 1), cy + dy * (hs + 1), cx + dx * (hs + 13), cy + dy * (hs + 13), col);
    if (on('engaged')) drawRows(ctx, SYM.ENG, cx - 4, cy - 4, PAL.AMB3);
    drawSymbol(ctx, key, cx, cy, col);
    if (on('hooked')) drawRows(ctx, SYM.HOOK, cx - 5, cy - 5, PAL.WHITE);
    if (on('lock')) { ctx.fillStyle = PAL.MAG1; ctx.fillRect(cx - 2, cy - hs - 3, 5, 1); ctx.fillRect(cx - 2, cy + hs + 3, 5, 1); }
    else if (on('radiating')) { ctx.fillStyle = PAL.MAG1; ctx.fillRect(cx - 1, cy - hs - 3, 3, 1); }
    if (on('label')) {
      drawText(ctx, '4005', cx + 8, cy - 12, 'mini', col);
      drawText(ctx, lab.cat === 'AIR' || lab.cat === 'MSL' ? '480' : '39', cx + 8, cy - 6, 'mini', col);
    }
    // the words
    const c = CATS.find((x) => x.cat === lab.cat);
    const said = [`<strong>${esc(i.name)}</strong> (<code>${i.idn}</code>), ${esc(c.name.toLowerCase())}. ${esc(i.text)} ${esc(c.text)}`];
    for (const s of LAB_STATES) if (on(s.id) && s.text) said.push(`<strong>${esc(s.name)}:</strong> ${esc(s.text)}`);
    $('lab-say').innerHTML = said.join('<br>');
    $('lab-hdg-v').textContent = String(lab.hdg).padStart(3, '0') + '°';
    for (const b of document.querySelectorAll('#lab-idn .chip')) b.setAttribute('aria-pressed', b.dataset.v === lab.idn);
    for (const b of document.querySelectorAll('#lab-cat .chip')) b.setAttribute('aria-pressed', b.dataset.v === lab.cat);
    for (const b of document.querySelectorAll('#lab-state .chip')) b.setAttribute('aria-pressed', lab.on.has(b.dataset.v));
    for (const b of document.querySelectorAll('#symgrid button')) b.classList.toggle('on', b.dataset.idn === lab.idn && b.dataset.cat === lab.cat);
  }
  function buildLab() {
    $('lab-idn').innerHTML = IDS.map((i) => `<button class="chip" data-v="${i.idn}" title="${esc(i.name)}">${i.idn}</button>`).join('');
    $('lab-cat').innerHTML = CATS.map((c) => `<button class="chip" data-v="${c.cat}">${esc(c.name)}</button>`).join('');
    $('lab-state').innerHTML = LAB_STATES.map((s) => `<button class="chip" data-v="${s.id}">${esc(s.name)}</button>`).join('');
    $('lab-idn').addEventListener('click', (ev) => { const b = ev.target.closest('.chip'); if (b) { lab.idn = b.dataset.v; drawLab(); } });
    $('lab-cat').addEventListener('click', (ev) => { const b = ev.target.closest('.chip'); if (b) { lab.cat = b.dataset.v; drawLab(); } });
    $('lab-state').addEventListener('click', (ev) => { const b = ev.target.closest('.chip'); if (!b) return; lab.on.has(b.dataset.v) ? lab.on.delete(b.dataset.v) : lab.on.add(b.dataset.v); drawLab(); });
    $('lab-hdg').addEventListener('input', (ev) => { lab.hdg = Number(ev.target.value); drawLab(); });
    drawLab();
  }
  function buildMarks() {
    const m = $('marks');
    for (const k of G.symbology.marks) {
      const rows = SYM[k.frame];
      const d = document.createElement('div'); d.className = 'mark-card';
      const cv = canvasFor(rows[0].length + 4, rows.length + 4, 3);
      drawSymbol(cv.getContext('2d'), k.frame, (rows[0].length + 4) >> 1, (rows.length + 4) >> 1, PAL[k.color]);
      d.appendChild(cv);
      d.insertAdjacentHTML('beforeend', `<div><b>${esc(k.title)}</b><span>${md(k.text)}</span></div>`);
      m.appendChild(d);
    }
    $('elements').innerHTML = G.symbology.elements.map((x) => `<dt>${esc(x.title)}</dt><dd>${md(x.text)}</dd>`).join('');
    $('effects').innerHTML = G.symbology.effects.map((x) => `<dt>${esc(x.name)}</dt><dd>${md(x.text)}</dd>`).join('');
  }

  // ------------------------------------------------------------------------------------ lessons
  function buildLessons() {
    $('lessonlist').innerHTML = G.lessons.map((l) => `
      <details class="lesson"${l.no === 1 ? ' open' : ''}>
        <summary><span class="n">${l.no}</span><span class="t">${esc(l.title)}</span><span class="b">${esc(l.intro)}</span></summary>
        <div class="lesson-body"><ol class="steps">${l.steps.map((s) => `
          <li class="${s.act ? 'act' : ''}">
            ${s.alert ? `<p class="alertq">${esc(s.alert)}</p>` : ''}
            <p class="say">${esc(s.say)}</p>
            ${s.act ? `<div class="do"><span class="dl">DO</span><span class="dh">${esc(s.hint)}</span>${s.named.map((id) => E[id] && E[id].where.length ? whereChips(id, { max: 2 }) : `<button class="chip where" data-e="${esc(id)}">${esc(E[id] ? E[id].title : id)}</button>`).join(' ')}</div>` : ''}
          </li>`).join('')}</ol></div>
      </details>`).join('');
  }

  // ------------------------------------------------------------------------------------ mission
  function buildMission() {
    const M = G.mission;
    const bands = M.bands.map((b) => { const i = b.indexOf(':'); return `<tr><td>${esc(b.slice(0, i))}</td><td>${esc(b.slice(i + 1).trim())}</td></tr>`; }).join('');
    $('missionbody').innerHTML = `
      <p><strong>01 ${esc(M.title)}</strong>. ${esc(M.intro)}</p>
      <p class="lbl" style="margin-top:18px">The orders, as the briefing gives them</p>
      <div class="quote">${M.brief.map((l) => `<p>${esc(l)}</p>`).join('')}</div>
      <div class="quote">${M.plain.map((l) => `<p>${esc(l)}</p>`).join('')}</div>
      <h3>Objectives</h3>
      <ul class="obj">${M.objectives.map((o) => `<li><span class="tag ${o.required ? 'req' : 'opt'}">${o.required ? 'REQ' : 'OPT'}</span><span>${esc(o.text)}</span></li>`).join('')}</ul>
      <p style="font-size:0.9rem;color:var(--frame7)">Fail any <code>REQ</code> objective and the mission is lost. ${M.minutes} minutes. Par ${M.par}.</p>
      <h3>Who is out there</h3>
      <div class="tablewrap"><table><tbody>${M.cast.map((c) => `<tr><td>${esc(c.who)}</td><td>${esc(c.what)}</td></tr>`).join('')}</tbody></table></div>
      <h3>How it unfolds</h3>
      <ol class="timeline">${M.phases.map((p) => `<li><span class="at">${esc(p.at)}</span><b>${esc(p.title)}</b>${md(p.text)}</li>`).join('')}</ol>
      <h3>Tips</h3>
      <ul>${M.tips.map((t) => `<li>${md(t)}</li>`).join('')}</ul>
      <h3>Grades for this mission</h3>
      <div class="tablewrap"><table><tbody>${bands}</tbody></table></div>`;
  }

  // ------------------------------------------------------------------------------------ alerts
  const LEVELS = ['all', 'crit', 'warn', 'info', 'alarm', 'fault'];
  let alertLevel = 'all';
  function buildAlerts() {
    $('alertfilter').innerHTML = LEVELS.map((l) => `<button class="chip" data-v="${l}">${{ all: 'All', crit: 'Critical (red)', warn: 'Warning (amber)', info: 'Information (green)', alarm: 'Alarm', fault: 'Fault' }[l]}</button>`).join('');
    $('alertfilter').addEventListener('click', (ev) => { const b = ev.target.closest('.chip'); if (b) { alertLevel = b.dataset.v; drawAlerts(); } });
    drawAlerts();
  }
  function drawAlerts() {
    for (const b of $('alertfilter').children) b.setAttribute('aria-pressed', b.dataset.v === alertLevel);
    $('alertlist').innerHTML = G.alerts.filter((a) => alertLevel === 'all' || a.level === alertLevel)
      .map((a) => `<div class="al ${a.level}"><code>${esc(a.text)}</code><p class="m">${md(a.meaning)}</p><p class="a">${md(a.action)}</p></div>`).join('');
  }

  // ------------------------------------------------------------------------------------ glossary
  function drawGloss(filter = '') {
    const f = filter.trim().toLowerCase();
    $('glosslist').innerHTML = G.glossary.filter((g) => !f || g.term.toLowerCase().includes(f) || g.def.toLowerCase().includes(f))
      .map((g) => `<div><dt>${esc(g.term)}</dt><dd>${esc(g.def)}</dd>${g.e ? `<span class="more">${xref(g.e, 'More →')}</span>` : '<span></span>'}</div>`).join('');
  }

  // ------------------------------------------------------------------------------------ controls & menus
  function buildControls() {
    const g = Object.values(E).filter((e) => e.section === 'gestures' || e.id === 'menu:track');
    $('gestures').innerHTML = `<dl class="defs">${g.map((e) => `<dt>${esc(e.title)}</dt><dd>${md(e.summary)} ${e.body.map(md).join(' ')}</dd>`).join('')}</dl>`;
    const keyed = Object.values(E).filter((e) => e.kbd.length);
    $('kbdlist').innerHTML = keyed.map((e) => `<tr><td>${e.kbd.map((k) => `<kbd>${esc(k)}</kbd>`).join(' ')}</td><td>${xref(e.id, e.title)}</td></tr>`).join('') +
      G.keyboard.map((k) => `<tr><td><kbd>${esc(k.keys)}</kbd></td><td>${esc(k.does)}</td></tr>`).join('');
  }
  function buildMenus() {
    const S = G.scoring;
    const pct = (x) => `${Math.round(x * 100)}%`;
    const band = S.bands.map(([at, g], i) => `<tr><td>${g}</td><td>${at === null ? `below ${pct(S.bands[i - 1][0])} of par, or any lost mission` : `${pct(at)} of par or more`}</td></tr>`).join('');
    $('menubody').innerHTML = `
      <h3>Main menu</h3>
      <div class="tablewrap"><table><tbody>${G.screens.map((s) => `<tr><td>${esc(s.name)}</td><td>${md(s.text)}</td></tr>`).join('')}</tbody></table></div>
      <h3>Settings</h3>
      <div class="tablewrap"><table><thead><tr><th>Setting</th><th>Values</th><th>Default</th><th></th></tr></thead><tbody>${G.settings.map((s) => `<tr><td>${esc(s.name)}</td><td>${esc(s.values)}</td><td>${esc(s.def)}</td><td>${md(s.text)}</td></tr>`).join('')}</tbody></table></div>
      <h3>Pause menu and debrief</h3>
      <p>${xref('screen:pause', 'The pause menu')} · ${xref('screen:debrief', 'The debrief')}</p>
      <h3 id="scoring">Scoring</h3>
      <p>${md(E['concept:scoring'].body.join(' '))}</p>
      <div class="tablewrap"><table><thead><tr><th>Grade</th><th>Score</th></tr></thead><tbody>${band}</tbody></table></div>
      <div class="tablewrap"><table><thead><tr><th>Points for</th><th></th></tr></thead><tbody>
        <tr><td>Each required objective met</td><td>+${S.objective.required}</td></tr>
        <tr><td>Each optional objective met</td><td>+${S.objective.optional}</td></tr>
        ${Object.entries(S.kill).filter(([, v]) => v > 0).map(([k, v]) => `<tr><td>Destroying a hostile ${esc(k)}</td><td>+${v}</td></tr>`).join('')}
        <tr><td>Hull lost</td><td>−${S.hull} × the fraction lost</td></tr>
        <tr><td>Each enemy weapon that hits (leaker)</td><td>−${S.leaker}</td></tr>
        <tr><td>Each neutral or friendly destroyed</td><td>−${S.blueOnWhite}</td></tr>
        <tr><td>Rounds fired</td><td>${Object.entries(S.rounds).map(([k, v]) => `${esc(k)} −${v}`).join(', ')}</td></tr>
      </tbody></table></div>`;
  }

  // ------------------------------------------------------------------------------------ boot
  $('asof').textContent = `Every key, page, symbol and alert on the console. Version ${G.meta.version}.`;
  $('built').textContent = `Built from the game, version ${G.meta.version} (${G.meta.commit}), on ${G.meta.built}. Console photographs: mission 1 at ${Math.floor(G.meta.t / 60)}:${String(G.meta.t % 60).padStart(2, '0')}.`;
  setShot('ops-1');
  buildGrid(); buildLab(); buildMarks(); buildLessons(); buildMission(); buildAlerts(); drawGloss(); buildControls(); buildMenus();
  $('gq').addEventListener('input', (ev) => drawGloss(ev.target.value));
  // deep links: guide/#e=key:DECOY opens that entry
  const m = /^#e=(.+)$/.exec(location.hash);
  if (m && E[decodeURIComponent(m[1])]) open(decodeURIComponent(m[1]));
})();
